### ISSUE TITLE
man pages not installed correctly

### ISSUE THREAD

**Issue by weitjong** [cognusion/fuse-copyfs#2]
I have successfully built and installed ```copyfs``` on my 64-bit Fedora. It needs a few devel software packages that I didn't have before but it is not difficult to figure out which one to get a successful build. It would be great if the README.md can list out all the required software packages. Anyway, the ```copyfs``` installed almost flawlessly. The only problem I encountered was the man pages being installed at the ```/man/man1``` instead of ```/usr/share/man/man1```. I believe the latter is the correct installation location for both Redhat-based and Debian-based distros.

**Comment by cognusion** [comment]
I haven't looked into where/why this is happening, but it is all handled by the autoconf system when you run "configure". Feel free to submit a pull request if you figure it out.

    mandir=@mandir@

**Comment by weitjong** [comment]
I think I know why. The ```configure``` script was too old. I ran this command below to update the ```configure``` script automatically.
```
autoreconf -i
```

**Comment by cognusion** [comment]
Ran autoreconf -i for a new configure - reopen if it's still a problem. Thank you for tracking this down!
